### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by anrom7** [muliarska/homeworks_ucu#1]
Україномовного цікавіше. Потрібно визначитися що думаєте робити. Сентимент аналіз тесту це одне а встановлення настрою мовця (того хто пише) це інше. Ви схиляєтесь до другого, але я не бачу даних на основі чого ви це будете робити. Twitter API не дасть Вам потрібних даних. Опрацювання текстів це NLP. Матеріали по NLP 5)ACL Anthology https://aclanthology.coli.uni-saarland.de/ 6)A curated list of resources dedicated to Natural Language Processing (NLP) - https://github.com/keon/awesome-nlp 7) Tracking Progress in Natural Language Processing - https://github.com/sebastianruder/NLP-progress. Починайте з nltk.org   
Тема: ?

**Comment by muliarska** [comment]
1) Я думала над українською. Проте україномовних користувачів в Twitter набагато менше, та мені не вдалося знайти таких даних, які я хотіла українською. Тому думаю, що залишуся на англомовних користувачах.

2) Я розумію, що настрій - це трохи інше. Але в даних, які я знайшла, для кожного слова показує відсоток різних емоцій (страх, радість, сум, відраза та інші). Тобто можна вирахувати, який настрій в користувача через ці відсотки. Наприклад, зі всіх слів, які вдалось проаналізувати радість становить 70%, отже це основна емоції. Решту емоцій теж можна вивести з їхніми частинами.

3) Twitter API дає доступ до твітів користувача, як я і показувала в Python модулі. Також можна шукати твіти за хештегами, які використовував корситувач, чи аналізувати твіти людей, яких він позначав. Якщо я тут помиляюся, напишіть будь ласка.

4) Дякую вам за час та ресурси. 
Напишіть будь ласка, що Ви думаєте щодо цього та як порадите бути з темою. Дякую

**Comment by anrom7** [comment]
2. Я думаю що це емоції читача, а не мовця. Прочитайте уважно. Я знаю що настрої мовця є тут https://mpqa.cs.pitt.edu/corpora/mpqa_corpus/

**Comment by muliarska** [comment]
Я скачала ці дані, але мені не всі з них вдалося відкрити та розібратися.
А чи взагалі відрізняються емоції читача від емоцій мовця, якщо не враховувати інтонацію, яка відсутня в тексті?
Будь-які особисті вподобання важко передбачити (такі як чиясь ненависть до слова "гречка", наприклад). 
В даних є загальні поставлені емоції, які спільні і для мовця, і для читача.

**Comment by anrom7** [comment]
Дані я дав як приклад. Ви не обов'язково повинні їх використовувати. Те що емоції читача відрізняються від емоцій мовця це однозначно. 
Сентимент аналіз (аналіз тональності) це добре досліджена тема і тут важко попасти в глухий кут. Якщо Ви обираєте це то даних є достатньо. Якщо Ви все ж таки хочете настрій мовця визначати то потрібно знайти такі дані.  Дані https://competitions.codalab.org/competitions/17751#learn_the_details-resources . Що з ними роблять https://www.researchgate.net/publication/337498446_Emotion_Detection_from_Tweets_using_AIT-2018_Dataset 
Ту частину що зрозумієте робіть як ДЗ.

**Comment by muliarska** [comment]
Окей, я наче розібралась та знайшла дані, щоб визначати емоції мовця, а не сентимент.
Тоді моєю темою дз буде: “Виведення статистики про настрій, емоційний стан англомовного користувача та порад, як їх покращити, на основі аналізу його твітів та хештегів за останній час” ?

**Comment by anrom7** [comment]
Чудово. Дуже довга назва. Спробуємо щось коротше. 
Тема: Встановлення настрою та емоційного стану користувача Twitter.
