### ISSUE TITLE
ДЗ2

### ISSUE THREAD

**Issue by anrom7** [muliarska/homeworks_ucu#2]
README.md - ?
 Бази даних це не txt файли

**Comment by muliarska** [comment]
README в процесі зараз, скоро буде.
Щодо txt файлів, я, мабуть, некоректно вжила слово "база даних". 
Я зараз треную модель на txt файлах, якщо я просто всюди заберу слова "база даних" буде добре? 
Чи потрібно використовувати саме базу даних в моєму випадку, а не txt файли?

**Comment by anrom7** [comment]
Ви тренуєте на даних. Звідкілясь Ви берете ці дані  і про це розповідаєте звідки взяли.
